"""Pydantic models for the Recruiting Agent (#20, Agent2 Day 5)."""
from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

AtsPlatform = Literal["greenhouse", "lever", "ashby"]


class JdVariant(BaseModel):
    """One of the five JD tones generated by the agent."""

    tone: str
    text: str


class SourcingTemplate(BaseModel):
    channel: Literal["linkedin", "email", "other"] = "linkedin"
    subject: str | None = None
    body: str
    notes: str | None = None


class GenerateRequisitionRequest(BaseModel):
    role_request: str = Field(..., min_length=4, max_length=4000)
    location: str | None = Field(default=None, max_length=200)
    department: str | None = Field(default=None, max_length=200)


class GenerateRequisitionResponse(BaseModel):
    id: str
    role_request: str
    jd_variants: list[JdVariant]
    sources: list[dict]
    created_at: datetime


class PublishRequisitionRequest(BaseModel):
    selected_variant_index: int = Field(..., ge=0, le=8)
    ats_platform: AtsPlatform
    hiring_manager_email: str | None = None
    slack_channel: str | None = None
    notion_parent_page_id: str | None = None


class RequisitionRead(BaseModel):
    id: str
    org_id: str
    created_by: str
    role_request: str
    jd_variants: list[JdVariant]
    selected_variant_index: int | None
    ats_platform: AtsPlatform | None
    ats_job_id: str | None
    ats_url: str | None
    notion_tracker_url: str | None
    sourcing_templates: list[SourcingTemplate]
    linkedin_search_urls: list[str]
    hiring_manager_email: str | None
    slack_channel: str | None
    status: Literal["draft", "published", "failed"]
    error_message: str | None
    created_at: datetime
    published_at: datetime | None
