"""Pydantic models for the Recruiting Agent (#20, Agent2 Day 5).

The supported ATS providers are Greenhouse, Lever, and Ashby.
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

# Union of every ATS we can publish to.
AtsPlatform = Literal["greenhouse", "lever", "ashby"]

# Destination kind retained in the posting result contract for future providers.
DestinationType = Literal["ats", "job_board"]

SeniorityLevel = Literal["intern", "entry", "mid", "senior", "staff", "lead"]


class JdVariant(BaseModel):
    """One of the five JD tones generated by the agent."""

    tone: str
    text: str


class SourcingTemplate(BaseModel):
    channel: Literal["linkedin", "email", "other"] = "linkedin"
    subject: str | None = None
    body: str
    notes: str | None = None


class LinkedinSearch(BaseModel):
    """One pre-built LinkedIn People-search deep link.

    `label` is the human-readable headline shown in the UI (e.g. "Senior
    Frontend Engineer"); `description` explains what filters/strategy the
    URL applies (e.g. "Title-only search, 2nd-degree connections").
    """

    label: str
    url: str
    description: str


class GenerateRequisitionRequest(BaseModel):
    role_request: str = Field(..., min_length=4, max_length=4000)
    location: str = Field(..., min_length=1, max_length=200)
    department: str = Field(..., min_length=1, max_length=200)
    seniority_level: SeniorityLevel
    # Quoted verbatim in every JD variant.
    disclosed_compensation: str = Field(..., min_length=1, max_length=300)
    # Free-text interview process: rounds, format, panel, timeline.
    # Included in the JD so candidates know what to expect.
    interview_details: str = Field(..., min_length=1, max_length=2000)
    # Tech stack required for the role — fed into KB facet queries and synthesis.
    stack: str | None = Field(default=None, max_length=1000)
    # Free-text working hours / schedule expectations (timezone, on-call, async norms).
    working_hours: str = Field(..., min_length=1, max_length=300)
    # Per-hire specifics fed into KB facet queries to disambiguate same-role hires.
    context_notes: str | None = Field(default=None, max_length=4000)


class GenerateRequisitionResponse(BaseModel):
    id: str
    role_request: str
    jd_variants: list[JdVariant]
    sources: list[dict]
    # False when no KB chunks matched any facet.
    grounded: bool
    created_at: datetime


class AtsPosting(BaseModel):
    """Result of publishing one requisition to one destination (ATS or job board).

    `error` is set instead of `job_id` / `url` when that platform failed.
    The requisition is still considered "published" as long as at least one
    platform succeeded — the failures are surfaced inline so the recruiter
    can retry the bad ones. `destination_type` carries the registry tag so
    the UI can render different copy for "ATS" vs "Job board" failures.
    """

    platform: AtsPlatform
    destination_type: DestinationType | None = None
    job_id: str | None = None
    url: str | None = None
    error: str | None = None


class PublishRequisitionRequest(BaseModel):
    selected_variant_index: int = Field(..., ge=0, le=4)
    # At least one platform required; deduped server-side to be safe.
    ats_platforms: list[AtsPlatform] = Field(..., min_length=1, max_length=3)
    hiring_manager_email: str | None = None
    slack_channel: str | None = None
    notion_parent_page_id: str | None = None
    location_override: str | None = Field(default=None, max_length=200)
    department_override: str | None = Field(default=None, max_length=200)
    # Per-platform mapping overrides keyed by platform name. Each value is the
    # same shape the single-platform flow used (office_ids, department_id …).
    mapping_overrides: dict[AtsPlatform, dict] | None = None


class JdVariantEdit(BaseModel):
    """Direct manual edit of one JD variant's markdown text."""

    variant_index: int = Field(ge=0)
    text: str = Field(min_length=1, max_length=32000)


class UpdateRequisitionRequest(BaseModel):
    """Edit a draft requisition. None = leave unchanged.

    Does not auto-regenerate variants — pass regenerate_variants=True explicitly.
    """

    role_request: str | None = Field(default=None, min_length=4, max_length=4000)
    location: str | None = Field(default=None, max_length=200)
    department: str | None = Field(default=None, max_length=200)
    seniority_level: SeniorityLevel | None = None
    disclosed_compensation: str | None = Field(default=None, max_length=300)
    interview_details: str | None = Field(default=None, max_length=2000)
    stack: str | None = Field(default=None, max_length=1000)
    working_hours: str | None = Field(default=None, max_length=300)
    context_notes: str | None = Field(default=None, max_length=4000)
    regenerate_variants: bool = False
    # Manual JD edit — replaces one variant's text in place. Mutually
    # exclusive with regenerate_variants (regeneration would clobber it).
    jd_variant_edit: JdVariantEdit | None = None


class CandidateRecord(BaseModel):
    """One candidate normalised across every ATS.

    Each ATS exposes candidates in a different shape — Greenhouse splits
    name into first/last + nested email arrays, Lever uses opportunities
    with a stage object, Ashby returns applications with embedded candidate
    info. We flatten all of them into this common shape so the Notion upsert
    layer doesn't need a per-platform branch.

    `external_id` is the ATS's candidate id (NOT application id) — stable
    across re-syncs even if the candidate moves through stages.
    """

    ats_platform: Literal["greenhouse", "lever", "ashby"]
    external_id: str
    full_name: str | None = None
    email: str | None = None
    phone: str | None = None
    current_company: str | None = None
    current_title: str | None = None
    # Free-text stage label from the ATS (e.g. "Phone Screen", "Onsite").
    # We don't normalise to a canonical pipeline because each ATS has its
    # own configurable stage taxonomy and forcing a mapping would lose
    # information.
    stage: str | None = None
    resume_url: str | None = None
    # Deep-link back to the candidate inside the ATS UI so a recruiter can
    # click through from the Notion row to take action.
    candidate_url: str | None = None
    applied_at: datetime | None = None


class SyncCandidatesResponse(BaseModel):
    """Result of an on-demand candidate sync.

    Reports a per-platform summary so the UI can show "Greenhouse: 12 new,
    3 updated; Lever: skipped (not connected)" rather than a single opaque
    count. `notion_db_url` is populated when the sync created the Notion
    database on first run.
    """

    requisition_id: str
    synced_at: datetime
    total_candidates: int
    new_candidates: int
    updated_candidates: int
    per_platform: dict[str, dict]
    notion_db_url: str | None = None
    errors: list[str] = Field(default_factory=list)


class RequisitionRead(BaseModel):
    id: str
    org_id: str
    created_by: str
    role_request: str
    location: str | None = None
    department: str | None = None
    seniority_level: SeniorityLevel | None
    disclosed_compensation: str | None
    interview_details: str | None
    stack: str | None
    working_hours: str | None = None
    context_notes: str | None
    grounded: bool
    jd_variants: list[JdVariant]
    selected_variant_index: int | None
    ats_platform: AtsPlatform | None
    ats_job_id: str | None
    ats_url: str | None
    ats_postings: list[AtsPosting] = Field(default_factory=list)
    notion_tracker_url: str | None
    sourcing_templates: list[SourcingTemplate]
    linkedin_search_urls: list[LinkedinSearch]
    hiring_manager_email: str | None
    slack_channel: str | None
    # Non-null when publish ran but the Slack post failed (e.g. bot wasn't a
    # member of the channel). UI surfaces this as an actionable amber card.
    slack_post_error: str | None = None
    status: Literal["draft", "published", "failed"]
    error_message: str | None
    created_at: datetime
    published_at: datetime | None
    # Candidate sync state — populated once the recruiter clicks
    # "Sync Candidates" on the requisition detail page. NULL until then.
    notion_candidates_db_id: str | None = None
    candidates_last_synced_at: datetime | None = None
    candidates_last_sync_error: str | None = None
    # Set once HR clicks "Hiring completed" on this requisition. NULL until then.
    hiring_completed_at: datetime | None = None
    # Archived rows are hidden from the default listing. Published requisitions
    # can't be deleted (audit trail), so archiving is their only retire path.
    archived_at: datetime | None = None
    archived_by: str | None = None
