import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { Markdown } from "@/components/chat/markdown";
import { PrintTrigger } from "./print-trigger";

const API_URL = process.env.API_URL ?? "http://localhost:8000";

interface PrintMessage {
  role: "user" | "assistant";
  content: string;
  sources: Array<{ document_name?: string | null; page_number?: number | null }> | null;
  created_at: string;
}

interface ExportPayload {
  conversation: {
    id: string;
    title: string | null;
    created_at: string;
    updated_at: string;
  };
  messages: PrintMessage[];
}

async function loadConversation(id: string): Promise<ExportPayload | null> {
  const supabase = await createClient();
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token;
  if (!token) return null;

  const res = await fetch(
    `${API_URL}/chat/conversations/${encodeURIComponent(id)}/export?format=json`,
    {
      headers: { Authorization: `Bearer ${token}` },
      cache: "no-store",
    },
  );
  if (res.status === 404) return null;
  if (!res.ok) return null;
  return (await res.json()) as ExportPayload;
}

export default async function PrintConversation({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const data = await loadConversation(id);
  if (data === null) {
    const supabase = await createClient();
    const { data: session } = await supabase.auth.getSession();
    if (!session.session) redirect(`/login?redirect=/print/conversation/${id}`);
    notFound();
  }

  const title = (data.conversation.title ?? "Conversation").trim();
  const exportedAt = new Date().toLocaleString(undefined, {
    dateStyle: "long",
    timeStyle: "short",
  });

  return (
    <div className="min-h-screen bg-white text-gray-900">
      <div className="mx-auto max-w-2xl px-6 py-10 print:px-0 print:py-0">
        <style>{`
            @media print {
              .no-print { display: none !important; }
              body { font-size: 11pt; color: #111827; }
              h1 { font-size: 18pt; }
              hr { border: 0; border-top: 1px solid #e5e7eb; }
            }
            @page { margin: 2cm; }
          `}</style>

          <div className="no-print mb-6 flex items-center justify-between">
            <p className="text-xs text-gray-500">
              Use your browser&apos;s print dialog (Ctrl/Cmd+P) to save as PDF.
            </p>
            <PrintTrigger />
          </div>

          <h1 className="mb-1 text-2xl font-semibold tracking-tight">
            {title}
          </h1>
          <p className="mb-6 text-xs text-gray-500">
            Exported from Nirnaya IQ · {exportedAt}
          </p>
          <hr className="mb-6" />

          {data.messages.map((m, i) => (
            <div key={i} className="mb-6 break-inside-avoid">
              <p className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-gray-400">
                {m.role === "user" ? "You" : "Nirnaya IQ"}
              </p>
              <div className="prose prose-sm max-w-none text-gray-900">
                <Markdown>{m.content}</Markdown>
              </div>
              {m.sources && m.sources.length > 0 && (
                <p className="mt-2 text-[11px] italic text-gray-500">
                  Sources:{" "}
                  {m.sources
                    .map((s) => s.document_name ?? "Untitled")
                    .filter(Boolean)
                    .slice(0, 5)
                    .join(", ")}
                </p>
              )}
              <hr className="mt-5" />
            </div>
          ))}

        <p className="mt-6 text-center text-[10px] text-gray-300">
          Generated by Nirnaya IQ
        </p>
      </div>
    </div>
  );
}
