import Link from "next/link";
import { Brain, FileText } from "lucide-react";
import { Markdown } from "@/components/chat/markdown";

const API_URL = process.env.API_URL ?? "http://localhost:8000";

interface SharedOutput {
  content: string;
  sources: Array<{ document_name?: string | null; page_number?: number | null }>;
  org_name: string | null;
  created_at: string;
  shared_at: string;
}

interface ErrorPayload {
  code?: string;
  message?: string;
}

async function loadShared(token: string): Promise<SharedOutput | { error: ErrorPayload }> {
  try {
    const res = await fetch(`${API_URL}/share/${encodeURIComponent(token)}`, {
      cache: "no-store",
    });
    if (!res.ok) {
      const body = (await res.json().catch(() => ({}))) as ErrorPayload;
      return { error: body };
    }
    return (await res.json()) as SharedOutput;
  } catch {
    return {
      error: { code: "network_error", message: "Couldn't load this link right now." },
    };
  }
}

export const metadata = {
  title: "Shared output",
  // The share page should not be indexed — we don't want random crawlers
  // archiving snapshots of internal company outputs.
  robots: { index: false, follow: false },
};

export default async function SharePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const data = await loadShared(token);

  if ("error" in data) {
    return <NotFoundState message={data.error.message ?? null} />;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50/60 to-white text-foreground dark:from-gray-900 dark:to-gray-950">
      <div className="mx-auto max-w-2xl px-4 py-10 sm:py-16">
        <div className="mb-6 flex items-center gap-2">
          <Brain className="h-5 w-5 text-primary" />
          <span className="text-sm font-medium text-muted-foreground">
            {data.org_name ?? "A workspace"} · Company Brain
          </span>
        </div>

        <div className="rounded-2xl border border-border bg-background p-6 shadow-sm">
          <div className="prose prose-sm max-w-none dark:prose-invert">
            <Markdown>{data.content}</Markdown>
          </div>

          {data.sources && data.sources.length > 0 && (
            <div className="mt-5 border-t border-border pt-4">
              <p className="mb-2 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
                Based on
              </p>
              <div className="flex flex-wrap gap-2">
                {data.sources.map((s, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center gap-1 rounded-full bg-muted px-2 py-0.5 text-[11px] text-muted-foreground"
                  >
                    <FileText className="h-3 w-3" />
                    {s.document_name ?? "Untitled"}
                    {s.page_number ? (
                      <span className="text-muted-foreground/70">
                        · p. {s.page_number}
                      </span>
                    ) : null}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="mt-6 text-center">
          <p className="mb-3 text-sm text-muted-foreground">
            This was generated by Company Brain — an AI knowledge base for teams.
          </p>
          <Link
            href="/signup"
            className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Create your own Company Brain →
          </Link>
        </div>
      </div>
    </div>
  );
}

function NotFoundState({ message }: { message: string | null }) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background px-6 text-center">
      <div className="rounded-full bg-muted p-3">
        <Brain className="h-6 w-6 text-muted-foreground" />
      </div>
      <h1 className="mt-4 text-xl font-semibold tracking-tight">
        This link no longer works
      </h1>
      <p className="mt-2 max-w-md text-sm text-muted-foreground">
        {message ??
          "The author may have revoked it, or the workspace turned off shared links."}
      </p>
      <Link
        href="/"
        className="mt-6 text-sm font-medium text-primary hover:underline"
      >
        Learn more about Company Brain →
      </Link>
    </div>
  );
}
