"""Google Docs API adapter (raw httpx).

Surface:
  create_briefing_doc(title, sections, user_id, org_id) -> {doc_id, url}

We use only two endpoints:
  POST https://docs.googleapis.com/v1/documents          create empty doc
  POST https://docs.googleapis.com/v1/documents/{id}:batchUpdate
                                                         insert structured content

Why not the official client:
    Same calculus as gmail.py / drive.py — one more SDK ships behind the curtain
    a giant transitive graph (grpcio, google-auth, etc.) we don't need. The two
    endpoints here are stable and the JSON shape is well-documented.

Doc structure produced:
    Title (heading 1)
    "Generated by Contexo on <ts>" (italic small text)
    Per-section: heading 2 + body paragraph(s)
"""
from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

import httpx

from app.services.integrations.google_workspace import get_user_token

log = logging.getLogger(__name__)

_DOCS_API = "https://docs.googleapis.com/v1"


async def create_briefing_doc(
    *,
    org_id: str,
    user_id: str,
    title: str,
    sections: dict[str, str],
) -> dict[str, Any]:
    """Create a Google Doc with title + per-section headings + bodies.

    sections shape: {"Executive Summary": "...", "Market Context": "...", ...}
    Order preserved from dict insertion order (3.7+).

    Returns {doc_id, url}.
    """
    token = await get_user_token(org_id=org_id, user_id=user_id)
    if not token:
        raise PermissionError("google_workspace_not_connected")

    async with httpx.AsyncClient(timeout=httpx.Timeout(30.0)) as client:
        # Step 1: create empty doc.
        create_resp = await client.post(
            f"{_DOCS_API}/documents",
            json={"title": title[:255]},
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
        )
        if create_resp.status_code == 401:
            raise PermissionError("google_docs_unauthorized")
        if create_resp.status_code >= 400:
            raise RuntimeError(
                f"google_docs_create_failed: {create_resp.status_code} {create_resp.text[:200]}"
            )
        doc = create_resp.json()
        doc_id = doc["documentId"]

        # Step 2: insert content via batchUpdate.
        # We build the requests in reverse-section order because every
        # insertText with index=1 shifts subsequent content — easier to
        # build the entire document with one InsertText then style each
        # range.
        requests = _build_doc_requests(title=title, sections=sections)
        update_resp = await client.post(
            f"{_DOCS_API}/documents/{doc_id}:batchUpdate",
            json={"requests": requests},
            headers={
                "Authorization": f"Bearer {token}",
                "Content-Type": "application/json",
            },
        )
        if update_resp.status_code >= 400:
            log.warning(
                "google_docs_update_failed status=%s body=%s",
                update_resp.status_code,
                update_resp.text[:300],
            )
            # Don't raise — the doc exists (just empty); the user can still
            # see it. Return what we have.
        url = f"https://docs.google.com/document/d/{doc_id}/edit"
        return {"doc_id": doc_id, "url": url}


def _build_doc_requests(*, title: str, sections: dict[str, str]) -> list[dict[str, Any]]:
    """Construct the batchUpdate requests array.

    Strategy: build one big text blob, insert it at index 1, then style the
    heading ranges (NAMED_STYLE_TYPE) by computing exact character offsets as
    we go. Newlines count as one character each in Google Docs.
    """
    blob_lines: list[tuple[str, str]] = []  # [(text, style)]
    # Title line.
    blob_lines.append((f"{title}\n", "TITLE"))
    blob_lines.append(
        (
            f"Generated by Contexo — {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}\n\n",
            "SUBTITLE",
        )
    )
    for heading, body in sections.items():
        if not (body or "").strip():
            continue
        blob_lines.append((f"{heading}\n", "HEADING_1"))
        blob_lines.append((f"{(body or '').strip()}\n\n", "NORMAL_TEXT"))

    full_text = "".join(seg for seg, _ in blob_lines)

    requests: list[dict[str, Any]] = [
        {
            "insertText": {
                "location": {"index": 1},
                "text": full_text,
            }
        }
    ]

    # Compute style ranges. Docs API indexes are 1-based; index 1 is the
    # first character. Each segment's range is [cursor, cursor + len(text)).
    cursor = 1
    for text, style in blob_lines:
        if style != "NORMAL_TEXT":
            requests.append(
                {
                    "updateParagraphStyle": {
                        "range": {
                            "startIndex": cursor,
                            "endIndex": cursor + len(text),
                        },
                        "paragraphStyle": {"namedStyleType": style},
                        "fields": "namedStyleType",
                    }
                }
            )
        cursor += len(text)

    return requests
